# Site settings
baseURL = "http://association-tedua.fr"
languageCode = "en-us"
title = "TeDua te bienvenue"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Association TeDua"
  description = "Domaine de l'expression libre. Car ICI, terre d'accueil enfin. Pour l'expression libre..."

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Cette page n'a pas pu être trouvée"
    text = "Visite plutôt: www.association-tedua.fr pour y trouver la bonne information."

  # Navigation Section
  [params.navigation]
    menu = "Menu"
    # Optional logo as brand stored in img/
    #logo = "logo.jpg"

    [[params.navigation.links]]
      name = "Vue générale"
      url = "#"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
    [[params.navigation.button1]]
      name = "Nous LIRE"
      url = "blogs"

  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Six jours de Jeu au Cerisier"
    subtitle = "Domaine de l'expression libre. Car ICI: terre d'accueil. Pour l'expression libre..."
    buttonText = "VIENS!"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.

    [[params.tiles.showcase]]
      title = "Chemin(s) de la semaine"
      subtitle = "Stage de théâtre et Répétitions quotidiennes ouvertes au public, Création & Spectacle grand public, Spectacle pour enfants, Apéritifs, Repas, Atelier de réflexion et conversation sur la Diffusion de spectacles... De l'élève au maître. De l'acteur au metteur en scène. Et toujours, au Public... [clique ici-->]"
      image = "pic02.jpg"
      url = "blogs/chemins-de-la-semaine"

    [[params.tiles.showcase]]
      title = "Artistes & Faiseurs"
      subtitle = "Plus de 30 comédiens, enseignant, metteur en scène, auteur, musiciens, artisans, et hôtes feront cette semaine-là. Au service du Public. Viens rencontrer leurs expressions... [clique ici-->]"
      image = "pic03.jpg"
      url = "blogs/artistes-et-faiseurs"

    [[params.tiles.showcase]]
      title = "Le Déj': Diffuseurs & Numérique?"
      subtitle = "L'art n'est là que pour autrui. Et là est précisément le pouvoir du diffuseur: d'où l'art doit-il être vu? pendant ces 2 heures de pause-déjeuner, 3 intervenants de Bordeaux, Lyon et Paris partageront leur vision du travail au croisement des arts vivants, outils numérique et des technologies libres pendant que... [clique ici-->]"
      image = "pic04.jpg"
      url = "blogs/le-déj-diffuseurs-et-numérique"

    [[params.tiles.showcase]]
      title = "Infos pratiques"
      subtitle = "Droit d'entrée pour la semaine. Transports et Plan pour venir au Cerisier [clique ici-->]"
      image = "pic06.jpg"
      url = "blogs/infos-pratiques"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "Vue d'ensemble"
    subtitle = "Qui, Pourquoi, Comment? Ici, des textes disent... [clique -->]"
    buttonText = "Viens lIRE"
    url = "blogs"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Envoyer un message"
    buttonClear = "Effacer"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Missive:"
    email = "diffusion@association-tedua.fr"

    [[params.contact.phone]]
    title = "Coup de Bigot (demander: Anne-Lucie Dumay)"
    phone = "0615609704"

    [[params.contact.address]]
    title = "Le Cerisier"
    street = "7-11 rue Joseph Brunet"
    city = "Bordeaux"
    country = "France"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Assocation TeDua"

    # Uses font awesome icons

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com/UBUntout/"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-github"
      url= "https://www.github.com"
      label = "GitHub"

    [[params.footer.quicklinks]]
      text = "Design:"
      url= "https://www.les-ethers-fertiles.blog"
      alt = "Les Ethers Fertiles"
